### ISSUE TITLE
Random stray line over the infield

### ISSUE THREAD

**Issue by MartnAR** [bdilday/GeomMLBStadiums#1]
Awesome work! But what bothers me is that the stadiums have a random stray line over the infield. 
![image](https://user-images.githubusercontent.com/9990814/43971824-244b3442-9c98-11e8-938f-6ae14cf4a8eb.png)

**Comment by bdilday** [comment]
Thanks for raising the issue - I noticed it but was putting off fixing it. Should be fixed with #2
